### ISSUE TITLE
Alphabetize these by company name

### ISSUE THREAD

**Issue by connorshea** [danluu/post-mortems#12]
If I can get permission, I'd gladly submit a PR to alphabetize these.

**Comment by danluu** [comment]
@connorshea, I don't have a super strong objection to that, but I'd prefer to categorize things somehow. I haven't thought through what categories make sense, though.

* Config errors
* Human error / manual operations
* Coding bugs. Maybe with a subsection for bugs in error checking, since those are unusually common.
* Hardware failures
* ???

No pressure or anything, but if you could come up with some kind of reasonable categorization scheme and submit a PR, I'd be really grateful! If not, I'll probably come up with some arbitrary scheme in the next few days.

**Comment by MathManiac0** [comment]
I was looking at the postmortems, and this is the main things I found:

- **Config Errors** (6 Postmortems)
- **Conflicts** (4 Postmortems)
- **Power/Hardware Failures** (3 Postmortems)
- **Unsorted** (~10 Postmortems)

Unsorted includes:
- Data Corruption
- Local File Deletion
- Unchecked Update
- Transation ID Wraparound
- Database Migration blocks critical tables; causes downtime
- Logging Error
- ELB
- Extensive preparations helped
- 'tilde S' key problem
- Healthcare.gov

Hope this helps!

**Comment by danluu** [comment]
Cool, thanks! Unless someone has already started on this, I'll try
reorganizing things into that structure when I get home and have access to
a non-work machine.

**Comment by danluu** [comment]
@MathManiac0 I did a rough pass at your classification scheme, but I didn't really check it to make sure that I moved stuff around correctly. As always, PRs/corrections welcome :-)

**Comment by MathManiac0** [comment]
Postmortems ordered and alphabetized in merged pull request #33.

**Comment by connorshea** [comment]
:tada: thanks @MathManiac0!
